title: Site
pages: 
  - default
  - aid
  - story
  - field-notes
fields:
  title:
    label: Title
    type:  text
  description:
    label: Description
    type:  textarea
  keywords:
    label: Keywords
    type:  tags
