title: Stack
pages: false
files:
  sortable: true
  fields:
    title:
      label: Title
      type: text
      required: false
    month:
      label: Month
      type:  text
      width: 1/3
    day:
      label: Day
      type:  text
      width: 1/3
    year:
      label: Year
      type:  text
      width: 1/3
    location:
      label: Location
      type:  text
    attribution:
      label: Attribution
      type: wysiwyg
    caption:
      label: Caption
      type: wysiwyg
    detail:
      label: Detail
      type:  selector
      mode:  single
      types:
        - image
fields:
  title:
    label: Title
    type:  text
  month:
    label: Month
    type:  text
    width: 1/3
  day:
    label: Day
    type:  text
    width: 1/3
  year:
    label: Year
    type:  text
    width: 1/3
  location:
    label: Location
    type:  text
  blocks:
    label: Blocks
    type: builder
    fieldsets:
      text:
        label: Text
        snippet: builder/text
        fields:
          text:
            label: Text
            type: wysiwyg
      quote:
        label: Quote
        snippet: builder/quote
        fields:
          text:
            label: Text
            type: wysiwyg
          month:
            label: Month
            type:  text
            width: 1/3
          day:
            label: Day
            type:  text
            width: 1/3
          year:
            label: Year
            type:  text
            width: 1/3
          location:
            label: Location
            type:  text
          attribution:
            label: Attribution
            type: wysiwyg
          size:
            label: Size
            type: select
            default: medium
            options:
              small: Small
              medium: Medium
              large: Large
      image:
        label: Image
        snippet: builder/image
        fields:
          image:
            label: Image
            type: image
          size:
            label: Size
            type: select
            default: medium
            options:
              small: Small
              medium: Medium
              large: Large
      video:
        label: Video
        snippet: builder/video
        fields:
          videoid:
            label: Video ID
            type: text
          source:
            label: Source
            type: select
            default: null
            options:
              youtube: YouTube
              vimeo: Vimeo
          title:
            label: Title
            type:  text
            required: false
          month:
            label: Month
            type:  text
            width: 1/3
          day:
            label: Day
            type:  text
            width: 1/3
          year:
            label: Year
            type:  text
            width: 1/3
          location:
            label: Location
            type:  text
          attribution:
            label: Attribution
            type: wysiwyg
          caption:
            label: Caption
            type:  wysiwyg
  thumb:
    label: Thumbnail
    type:  selector
    mode:  single
    types:
      - image
  excerpt:
    label: Excerpt
    type:  wysiwyg
  size:
    label: Size
    type: select
    default: small
    width: 1/4
    options:
      small: Small
      large: Large
  textSize:
    label: Text Size
    type: select
    default: smallText
    width: 1/4
    options:
      smallText: Small
      mediumText: Medium
      largeText: Large
  display:
    label: Display
    type: select
    default: image
    width: 1/4
    options:
      image: Image
      text: Text
  bw:
    label: Black & White
    type: toggle
    default: false
    text: yes/no
    width: 1/4